spring:
  application:
    name: eureka
  datasource:   #多数据源配置
    read:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://104.199.183.118:3306/hello-world?characterEncoding=UTF8&useSSL=false
      username: root
      password: root
    write:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://104.155.222.47:3306/hello-world?characterEncoding=UTF8&useSSL=false
      username: root
      password: root
    type: com.zaxxer.hikari.util.DriverDataSource
  http: #字符编码强制设为UTF-8
    encoding:
     charset: UTF-8
     enabled: true
     force: true
    converters:
      preferred-json-mapper: fastjson
  jpa: #jpa
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: li926893@163.com
    password: li926893
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
  thymeleaf:
    cache: false
    mode: LEGACYHTML5


server:
   port: 8761          # 指定该实例的端口
eureka:
  client:
    registerWithEureka: true  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
   hostname: localhost         # 指定该Eureka实例的主机名
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

# zuul 网关配置
zuul:

#  ignored-services:                        #需要忽视的服务(配置后将不会被路由)
  routes:
    back:
      path: /back/**
      serviceId: admin-back
  prefix: /api
  ignore-url: /auth/token
  token-header: access-token
  pub-key.path: D:\workspace\public.key
#mybatis相关配置
mybatis:
    type-aliases-package: com.junliang.spring.pojo.domain
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mybatis.xml
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL
    before: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
##mybatis -plus
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.junliang.spring.pojo.domain
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 3
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    #logic-delete-value: 0
#    #logic-not-delete-value: 1
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

jwt:
  rsa-public-key-file-path: D:\workspace\public.key
  rsa-private-key-file-path: D:\workspace\private.key
  token-header: access-token


